import type { Metadata } from 'next';
import ThemeProvider from '@/components/theme/theme-provider';
import './globals.css';

export const metadata: Metadata = {
	title: 'Baigiamasis darbas',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className="min-h-screen antialiased text-black dark:bg-linear-to-br dark:from-[#0f1117] dark:via-[#1a2040] dark:to-[#0f1117] dark:text-white">
				<ThemeProvider>{children}</ThemeProvider>
			</body>
		</html>
	);
}
