import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import ThemeProvider from '@/components/theme/theme-provider';
import './globals.css';

export const metadata: Metadata = {
	title: 'Baigiamasis darbas',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className="min-h-screen antialiased bg-slate-50 text-black dark:bg-slate-900 dark:text-white">
				<ThemeProvider>{children}</ThemeProvider>
			</body>
		</html>
	);
}
